### ISSUE TITLE
Dark mode toggle on/off

### ISSUE THREAD

**Issue by samarth29jc** [Curious-Ecosystem/Curious-Connect#103]
need dark mode which is an essential in modern website it lacks it so i could add that on home page so that User experience must not be compromised
@iam-harshit @manpreet244 @gnnandan @Sheetal-04

**Comment by CDCNaman** [comment]
@samarth29jc you can start working on it. 
Also Please Join to our [Onboarding Group](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN) and connect with @CDCJanhavi or any other member of UI/UX Team to discuss the appropriate Color Pallet

**Comment by thecuriousteam** [comment]
@samarth29jc our design is already in dark mode
