### ISSUE TITLE
[FEATURE] Create a 'Schedule Meeting' Page 

### ISSUE THREAD

**Issue by yashmandi** [Curious-Ecosystem/Curious-Connect#112]
## Feature Description
Creating a 'Schedule Meeting' Page where user can set-up meetings, can select time, date, duration, url, title of meeting, etc.

### Problem or Opportunity
Users will find it easy to set-up meetings in a reliable way.

### Proposed Solution
I have an idea for this page and would love to work on it under GSSOC '24

### Screenshot
I am talking about this section
![schedule-meet](https://github.com/Curious-Ecosystem/Curious-Connect/assets/132436131/74dbaada-4b7f-41e6-8a58-1867a0708dd7)

## **Instructions**

Stay you can start working on it by taking latest pull from main branch

- [ ] Please read the contributors guidelines [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the code of conduct [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to join onboarding group for knowledge flow and direct conversation and support from admins
- [ ] **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the screenshots and video of the development work once it is done 
- [ ] Contributions more than 3 will be awarded a certificate of appreciation from curious ecosystem 
- [ ] please mail to ([admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in)) for claiming certificate and please attach your issue number

Respect Co Developers And Please Reach-out to admins if any issues

**Comment by thecuriousteam** [comment]
Yes You can start working on it brother
