### ISSUE TITLE
Bug :  No Zod Validation in the Authentication 

### ISSUE THREAD

**Issue by ujjwalagrawal-1** [Curious-Ecosystem/Curious-Connect#133]
## **Describe the bug**
There is No Zod Validation in the Server Side Files 

It is Important to have  Zod in the files Because of following ->
**Zod** is a TypeScript-first schema declaration and validation library. Its importance lies in its ability to enforce data consistency, ensure data integrity, and improve code maintainability in TypeScript projects. Here are some elaborated points on the importance of Zod validation:

- **Type Safety:** Zod brings TypeScript's type safety to the validation process. It allows you to define schemas for your data structures using TypeScript types. This ensures that your data is validated at compile-time, catching errors early in the development process.

- **Declarative Schema Definition**: With Zod, you can declaratively define schemas for your data structures using a fluent API. This makes it easy to understand and maintain your validation rules, as they are defined alongside your TypeScript types.

- **Runtime Validation**: Zod not only provides compile-time type safety but also performs runtime validation of your data against the defined schemas. This ensures that your application only deals with valid data at runtime, reducing the risk of runtime errors due to invalid data.

- **Error Handling**: Zod provides detailed error messages when validation fails, including information about which part of the data failed validation and why. This makes it easier to debug validation issues and provide meaningful feedback to users.

- **Custom Validation Rules**: Zod allows you to define custom validation rules using predicates. This gives you flexibility in defining complex validation logic tailored to your specific requirements.

- **Integration with Frameworks**: Zod integrates well with popular JavaScript frameworks like React and Node.js, making it easy to incorporate validation into your application logic.

- **Immutable Data Structures:** Zod encourages the use of immutable data structures by returning validated data as immutable objects. This helps prevent unintended mutations of your data, leading to more predictable application behavior.

- **Data Consistency:** By enforcing validation rules on your data, Zod helps maintain consistency across your application. This ensures that data stored and processed in different parts of your application adheres to the same rules, reducing the risk of data inconsistencies.

- Improved Code Readability: With Zod, validation rules are defined alongside your TypeScript types, making your code more self-documenting and easier to understand for other developers.

## **Screenshots**
![image](https://github.com/Curious-Ecosystem/Curious-Connect/assets/122930278/f7604379-8646-46e6-ba1e-237927eb273d)
In above image we can see there not having any Zod Validation no one checking the Quality of email, password and username 

### **Expected behavior**
Will Show error if any user is making incorrect lenght password and also for invalid email's and many more..

**Comment by ujjwalagrawal-1** [comment]
@thecuriousteam  Please Allow me to create a Zod Schema and add validation to the Project.

please assign this issue to me

**Comment by thecuriousteam** [comment]
@ujjwalagrawal-1

## **Instructions**

You can start working on it by taking latest pull from main branch

- [ ] **Please raise pull request to `main`**
- [ ] Please read the **contributors guidelines** [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the **code of conduct** [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to **join onboarding group** for knowledge flow and direct conversation and support from admins
- [ ] **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the **screenshots and video of the development work** once it is done 
- [ ] Contributions more than **3 will be awarded a certificate of appreciation** from curious ecosystem 
- [ ] please mail to [admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in) for claiming certificate and please attach your issue number

if any help required reach-out to admins or mentors in the onboarding group default meeting link and approach to admins - **GOOGLE MEET** [Issue Discussion Google Meet](https://meet.google.com/bwp-aasw-xbk)

Respect Co Developers And Please Reach-out to admins if any issues

**Comment by Adhil523** [comment]
please assign this task to me as i have raised a similar issue based on authentication

**Comment by thecuriousteam** [comment]
yes @ujjwalagrawal-1 and @Adhil523 you can start working on this

## **Instructions**

You can start working on it by taking latest pull from main branch

- [ ] **Please raise pull request to `main`**
- [ ] Please read the **contributors guidelines** [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the **code of conduct** [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to **join onboarding group** for knowledge flow and direct conversation and support from admins
- [ ] **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the **screenshots and video of the development work** once it is done 
- [ ] Contributions more than **3 will be awarded a certificate of appreciation** from curious ecosystem 
- [ ] please mail to [admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in) for claiming certificate and please attach your issue number

if any help required reach-out to admins or mentors in the onboarding group default meeting link and approach to admins - **GOOGLE MEET** [Issue Discussion Google Meet](https://meet.google.com/bwp-aasw-xbk)

Respect Co Developers And Please Reach-out to admins if any issues

**Comment by ujjwalagrawal-1** [comment]
@thecuriousteam  Can you please Assign The Gssoc and level labels to it

**Comment by thecuriousteam** [comment]
@ujjwalagrawal-1 yoy can start working on it
