### ISSUE TITLE
[BUG] Invalid username Access 

### ISSUE THREAD

**Issue by ujjwalagrawal-1** [Curious-Ecosystem/Curious-Connect#152]
### Description

@curWhen Checking for the **Email,name, and password** if the user does not provide a name then it will get access to the website which is a bug 

### Screenshots

![image](https://github.com/Curious-Ecosystem/Curious-Connect/assets/122930278/1803a559-faf3-4c3d-925c-0781f93ad7fa)

### Checklist

- [X] I have checked the existing [issues](https://github.com/Curious-Ecosystem/Curious-Connect/issues).
- [X] I have read the [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md)
- [X] I have read the [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [X] I joined onboarding group for knowledge flow and direct conversation and support from admins  [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done 
- [X] If you need any help please join the default  ([Google Meet Link](https://meet.google.com/bwp-aasw-xbk))
- [X] I am willing to work on this issue (optional).

**Comment by thecuriousteam** [comment]
you can start working on this @ujjwalagrawal-1

**Comment by Tanishasi** [comment]
can i collaborate @ujjwalagrawal-1 ?

**Comment by thecuriousteam** [comment]
@Tanishasi

## **Instructions**

You can start working on it by taking latest pull from main branch

- [ ] **Please raise pull request to `main`**
- [ ] Please read the **contributors guidelines** [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the **code of conduct** [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to **join onboarding group** for knowledge flow and direct conversation and support from admins
- [ ] **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the **screenshots and video of the development work** once it is done 
- [ ] Contributions more than **3 will be awarded a certificate of appreciation** from curious ecosystem 
- [ ] please mail to [admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in) for claiming certificate and please attach your issue number

if any help required reach-out to admins or mentors in the onboarding group default meeting link and approach to admins - **GOOGLE MEET** [Issue Discussion Google Meet](https://meet.google.com/bwp-aasw-xbk)

Respect Co Developers And Please Reach-out to admins if any issues

**Comment by CDCNaman** [comment]
@ujjwalagrawal-1 Don't worry, we are reviewing your PR. We'll definitely provide you with the best rewards possible, either through GSSOC points for the leaderboard or any other opportunity. Just stay active on our project!
