### ISSUE TITLE
[BUG] Footer is not being seen due to Styling Errors

### ISSUE THREAD

**Issue by yashmandi** [Curious-Ecosystem/Curious-Connect#163]
### Description

As in the image below, the Sidebar Section is overtaking the Footer Section, which makes half of the Footer Section not visible.
I would like to fix this under GSSoC '24 as I've worked on this page earlier. 

![Screenshot (224)](https://github.com/Curious-Ecosystem/Curious-Connect/assets/132436131/9403b1c9-f50a-4c44-a0e1-c9b917325255)

### Checklist

- [x] I have checked the existing [issues](https://github.com/Curious-Ecosystem/Curious-Connect/issues).
- [X] I have read the [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md)
- [X] I have read the [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [X] I joined onboarding group for knowledge flow and direct conversation and support from admins  [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done 
- [X] If you need any help please join the default  ([Google Meet Link](https://meet.google.com/bwp-aasw-xbk))
- [X] I am willing to work on this issue (optional).

**Comment by niteshbca** [comment]
please assign me to task.

**Comment by 8deepakkumar8** [comment]
pls assign task to me

**Comment by Soumilgit** [comment]
please assign task to me

**Comment by sarthu210** [comment]
Hey can you please assign this task to me i will fix it and make it responsive by adding toggle buttons.

**Comment by yashmandi** [comment]
Issue is fixed under #181

**Comment by Sanujkumar** [comment]
I will be resolve this issues please assign to me in this task

**Comment by yashmandi** [comment]
Issue is already fixed under https://github.com/Curious-Ecosystem/Curious-Connect/pull/181
