### ISSUE TITLE
[Feature] Cookies Implementation 

### ISSUE THREAD

**Issue by rohit0033** [Curious-Ecosystem/Curious-Connect#166]
### Description

You have to implement cookies on the Authentication 

### Checklist

- [X] I have checked the existing [issues](https://github.com/Curious-Ecosystem/Curious-Connect/issues).
- [X] I have read the [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md)
- [X] I have read the [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [X] I joined onboarding group for knowledge flow and direct conversation and support from admins  [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done 
- [X] If you need any help please join the default  ([Google Meet Link](https://meet.google.com/bwp-aasw-xbk))

**Comment by Akki019** [comment]
Please assign this to me

**Comment by CDCNaman** [comment]
@Akki019 are you still working on it or not?
