### ISSUE TITLE
Favicon is missing 

### ISSUE THREAD

**Issue by PratikMane0112** [Curious-Ecosystem/Curious-Connect#169]
### Description

Current favicon is of default icon of react+vite .

### Screenshots

![Screenshot 2024-05-17 003005](https://github.com/Curious-Ecosystem/Curious-Connect/assets/153143167/30a11e03-a112-4cda-a794-1d92d2609977)

I will add a appropriate favicon which will match with website.

### Checklist

- [X] I have checked the existing [issues](https://github.com/Curious-Ecosystem/Curious-Connect/issues).
- [X] I have read the [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md)
- [X] I have read the [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [X] I joined onboarding group for knowledge flow and direct conversation and support from admins  [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done 
- [X] If you need any help please join the default  ([Google Meet Link](https://meet.google.com/bwp-aasw-xbk))

**Comment by thecuriousteam** [comment]
You can start working on this @PratikMane0112

**Comment by PratikMane0112** [comment]
Ok, Plz assign it to me.
