### ISSUE TITLE
404 Error page updating

### ISSUE THREAD

**Issue by PratikMane0112** [Curious-Ecosystem/Curious-Connect#170]
### Description

If we navigate through inappropriate route then 404 error page shows the footer section like below -

![Screenshot 2024-05-17 003626](https://github.com/Curious-Ecosystem/Curious-Connect/assets/153143167/bec83531-a67f-482a-aa42-f045aafc6045)

### Screenshots

I will add a page which describe the page neatly like below - 

![404-Page-Design-Examples](https://github.com/Curious-Ecosystem/Curious-Connect/assets/153143167/b56572e5-7bc2-49c0-a53e-9a9368621953)

Then I will append footer to below the image and button to navigate to homepage with responsiveness.

### Checklist

- [X] I have checked the existing [issues](https://github.com/Curious-Ecosystem/Curious-Connect/issues).
- [X] I have read the [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md)
- [X] I have read the [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [X] I joined onboarding group for knowledge flow and direct conversation and support from admins  [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done 
- [X] If you need any help please join the default  ([Google Meet Link](https://meet.google.com/bwp-aasw-xbk))

**Comment by thecuriousteam** [comment]
Yes you can work on it @PratikMane0112

**Comment by thecuriousteam** [comment]
Please instead of 404 give something like coming soon

**Comment by PratikMane0112** [comment]
Ok, I will do that.
