### ISSUE TITLE
Update existing  cards and contact section.

### ISSUE THREAD

**Issue by happyrao78** [Curious-Ecosystem/Curious-Connect#175]
### Description

1. Enhance the cards by providing them more better hover and tilt effects.
2. Update UI for the contact us form as currently it is not much appealing and interacting.
3. Provide the "what clients say" section on main home page with a marquee effect.

### Screenshots

![Screenshot 2024-05-17 112412](https://github.com/Curious-Ecosystem/Curious-Connect/assets/138770813/64ba16ec-ff9d-47bd-8ae3-501b951e5bbc)
![Screenshot 2024-05-17 112431](https://github.com/Curious-Ecosystem/Curious-Connect/assets/138770813/cc90f0e6-1fef-403e-ad66-3afdf09a14c4)

### Checklist

- [X] I have checked the existing [issues](https://github.com/Curious-Ecosystem/Curious-Connect/issues).
- [X] I have read the [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md)
- [X] I have read the [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [X] I joined onboarding group for knowledge flow and direct conversation and support from admins  [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done 
- [X] If you need any help please join the default  ([Google Meet Link](https://meet.google.com/bwp-aasw-xbk))

**Comment by thecuriousteam** [comment]
you can start working on this @happyrao78 

## **Instructions**

You can start working on it by taking latest pull from main branch

- [ ] **Please raise pull request to `main`**
- [ ] Please read the **contributors guidelines** [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the **code of conduct** [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to **join onboarding group** for knowledge flow and direct conversation and support from admins
- [ ] **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the **screenshots and video of the development work** once it is done 
- [ ] Contributions more than **3 will be awarded a certificate of appreciation** from curious ecosystem 
- [ ] please mail to [admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in) for claiming certificate and please attach your issue number

if any help required reach-out to admins or mentors in the onboarding group default meeting link and approach to admins - **GOOGLE MEET** [Issue Discussion Google Meet](https://meet.google.com/bwp-aasw-xbk)

Respect Co Developers And Please Reach-out to admins if any issues

**Comment by thecuriousteam** [comment]
no no don't do in curious ecosystem website

**Comment by thecuriousteam** [comment]
Please contribute for curious connect @happyrao78

**Comment by happyrao78** [comment]
@thecuriousteam Please assign me the task where I've applied before.
