### ISSUE TITLE
Data Submit Integration to Backend in 'Meeting Availability' Page

### ISSUE THREAD

**Issue by yashmandi** [Curious-Ecosystem/Curious-Connect#177]
### Description

When the mentor selects his availability on this page, that data should go out to backend.
Would like to work on this issue under GSSoC '24

![meeting-availability](https://github.com/Curious-Ecosystem/Curious-Connect/assets/132436131/360339b2-af6a-45c3-9755-b0964bf8676e)

### Checklist

- [X] I have checked the existing [issues](https://github.com/Curious-Ecosystem/Curious-Connect/issues).
- [X] I have read the [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md)
- [X] I have read the [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [X] I joined onboarding group for knowledge flow and direct conversation and support from admins  [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done 
- [X] If you need any help please join the default  ([Google Meet Link](https://meet.google.com/bwp-aasw-xbk))
- [X] I am willing to work on this issue (optional).

**Comment by thecuriousteam** [comment]
Yes @yashmandi ,You can start working on this
