### ISSUE TITLE
[JoinWithCode.jsx] -  Solve Flickering Issue In JoinWithCode.jsx for the landing page component.

### ISSUE THREAD

**Issue by CDCRishabh** [Curious-Ecosystem/Curious-Connect#184]
## **Task Description**

In this issue we have to solve a issue flickering in JoinWithCode.jsx  i.e. whenever anyone hovers on join room button the input box shifts a little right. 

## **Requirements:-**

Should be responsive.

Should be same as Figma design.

## **Goals and objectives**

To achieve the required output.

## **Branch Name**
PR Should be made in feature/InitialUIdesign Branch.
For more information, please read our [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).

## **Deadline**
20/05/2024

## **Priority**
Medium

## Additional Details
In order to understand the flow of the design here is the link of the [Figma file](https://www.figma.com/file/H968IpS2Bu9ifKeCWNFYw0/Untitled?type=design&node-id=0-1&mode=design).

## **Instructions**

You can start working on it by taking latest pull from main branch

- [ ] Please read the contributors guidelines [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the code of conduct [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to join onboarding group for knowledge flow and direct conversation and support from admins
- [ ] **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the screenshots and video of the development work once it is done 
- [ ] Contributions more than 3 will be awarded a certificate of appreciation from curious ecosystem 
- [ ] please mail to ([admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in)) for claiming certificate and please attach your issue number

Respect Co Developers And Please Reach-out to admins if any issues

**Comment by hars-21** [comment]
Please assign me. I'll work on it.

**Comment by nishant0708** [comment]
assign me this issue under gssoc24

**Comment by dipa-ghosh11** [comment]
> Hi there! This issue is still open. We are looking forward to your response. Assignees: None

I can fix this problem. Clearly this is an issue regarding responsive design. I can implement the functionality in no time and would stick to the figma design as required. Assign me this issue under gssoc2024 @CDCRishabh .

**Comment by hars-21** [comment]
Hey @thecuriousteam I have made PR. Please review

**Comment by sadvika05** [comment]
assign me this issue under gssoc24
