### ISSUE TITLE
[HeroSection .jsx] - Redesign Gradient  In HeroSection.jsx for the landing page component

### ISSUE THREAD

**Issue by CDCRishabh** [Curious-Ecosystem/Curious-Connect#186]
## **Task Description**

In this issue we have to redesign gradient in HeroSection.jsx  i.e. You have to redesign the gradient at the top right corner.

## **Requirements:-**

Should be responsive.
Color and size should be same 

## **Goals and objectives**

To achieve the required output.

## **Deadline**
20/05/2024

## **Priority**
Medium

## Additional Details
In order to understand the flow of the design here is the link of the [Figma file](https://www.figma.com/file/H968IpS2Bu9ifKeCWNFYw0/Untitled?type=design&node-id=0-1&mode=design).

## **Instructions**

You can start working on it by taking latest pull from main branch

- [ ] Please read the contributors guidelines [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the code of conduct [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to join onboarding group for knowledge flow and direct conversation and support from admins
- [ ] **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the screenshots and video of the development work once it is done 
- [ ] Contributions more than 3 will be awarded a certificate of appreciation from curious ecosystem 
- [ ] please mail to ([admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in)) for claiming certificate and please attach your issue number

Respect Co Developers And Please Reach-out to admins if any issues

![Screenshot 2024-05-17 180503](https://github.com/Curious-Ecosystem/Curious-Connect/assets/168666896/b12947b2-ca76-4505-8f28-010b4fda43c6)

**Comment by HareRamDwivedi** [comment]
I am a GSSOC contributor , I have a good experience in UI designing I can make it more visually appealing please assign me this issue under GSSOC 2024
