### ISSUE TITLE
[JoinWithCode.jsx] - Solve component's background color and input box's background color issue in  JoinWithCode.jsx for landing page.

### ISSUE THREAD

**Issue by CDCHarshit** [Curious-Ecosystem/Curious-Connect#187]
## **Task Description**

In this issue, we have to solve an issue of the component's background color and the input box's background color in JoinWithCode.jsx.

This is the current design:
![image](https://github.com/Curious-Ecosystem/Curious-Connect/assets/168666000/b979f3c9-4da3-46f3-802f-0b49832128ac)

And we need such a design
![image](https://github.com/Curious-Ecosystem/Curious-Connect/assets/168666000/14a746eb-0586-499d-998a-88062f1715c7)

-  Color code for component background color: **#15181D**
-  Color code for input box background color:  **#242830**

## **Requirements:-**

Should be responsive.

## **Instructions**

You can start working on it by taking latest pull from main branch

- [ ] Please read the contributors guidelines [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the code of conduct [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to join onboarding group for knowledge flow and direct conversation and support from admins
- [ ] **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the screenshots and video of the development work once it is done 
- [ ] Contributions more than 3 will be awarded a certificate of appreciation from curious ecosystem 
- [ ] please mail to ([admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in)) for claiming certificate and please attach your issue number

Respect Co Developers And Please Reach-out to admins if any issues

**Comment by somuwashere** [comment]
Hey, I want to work on this issue. can you please assign it to me if no one is working on it ?

**Comment by CDCHarshit** [comment]
@somuwashere you can start working on this issue.

**Comment by somuwashere** [comment]
Yes I m working on it

**Comment by CDCHarshit** [comment]
@somuwashere We are reviewing the PR. And soon you will get the update from our side. Till then stay tuned.

**Comment by PrakarshSingh5** [comment]
Please assign this project to me

**Comment by CDCHarshit** [comment]
The issue with the component's background color and the input box's background color in **JoinWithCode.jsx** has been resolved. The background colors have been adjusted to match the design specifications.

Thank you for your patience and contributions :)
