### ISSUE TITLE
[MeetingCards.jsx] - Redesigning meeting cards for landing pages in the MeetingCard.jsx component

### ISSUE THREAD

**Issue by CDCHarshit** [Curious-Ecosystem/Curious-Connect#188]
## **Task Description**

This issue involves you redesigning meeting cards for landing pages in the MeetingCards.jsx component.

This is the current design:

![image](https://github.com/Curious-Ecosystem/Curious-Connect/assets/168666000/bcee9ee0-8763-4c5a-bba0-a26960b06139)

And we need such a design:

![image](https://github.com/Curious-Ecosystem/Curious-Connect/assets/168666000/217aca56-0a07-4562-9faf-09a82239e62e)

**Note:** In the current design, the text appears on hover. But we need text below the icon.

-  Color code for 1st meeting card: **#FF742E**
-  Color code for 2nd meeting card:  **#0E78F9**
-  Color code for 3rd meeting card: **#830EF9**
-  Color code for 4th meeting card: **#F9A90E**

## **Requirements:-**

Should be responsive. And responsive design should look something like this on mobile devices:

![image](https://github.com/Curious-Ecosystem/Curious-Connect/assets/168666000/0f567234-ffff-47d9-ba63-0a060b58d078)

## **Instructions**

You can start working on it by taking latest pull from main branch

- [ ] Please read the contributors guidelines [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the code of conduct [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to join onboarding group for knowledge flow and direct conversation and support from admins
- [ ] **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the screenshots and video of the development work once it is done 
- [ ] Contributions more than 3 will be awarded a certificate of appreciation from curious ecosystem 
- [ ] please mail to ([admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in)) for claiming certificate and please attach your issue number

Respect Co Developers And Please Reach-out to admins if any issues

**Comment by anuragnegi000** [comment]
Assign this issue to me i would like to work on it

**Comment by CDCHarshit** [comment]
@anuragnegi000 you can start working on this issue.

**Comment by anuragnegi000** [comment]
@CDCHarshit okay

**Comment by nachatra-sharma** [comment]
@CDCHarshit sir, i want to work on this issue.

**Comment by harshcodesit** [comment]
My name is Harshwardhan Singh Panwar and I'm a contributor at GSSOC'24 .

idea:- By incorporating div CSS and animations, I can design the UI in an interactive manner, making it visually appealing.

Please assign this task to me, GSSOC'24 .

**Comment by harshcodesit** [comment]
please assign me as soon as possible

**Comment by CDCHarshit** [comment]
The issue with the component's redesigning meeting cards for landing pages in the **MeetingCards.jsx** has been resolved.

Thank you for your patience and contributions :)
