### ISSUE TITLE
[HeroSection.jsx] - Redesigning the Hero Component Image in HeroSection.jsx Component for Landing Page

### ISSUE THREAD

**Issue by CDCHarshit** [Curious-Ecosystem/Curious-Connect#189]
## **Task Description**

In this issue, you have to redesign the image on the right side of the hero component. In this, you will be able to see that the dot type which is coming in the vertical behind the image needs to be corrected in HeroSection.jsx for a landing page.

**Note:** For this you will use this UI library **https://ui.aceternity.com/components/hero-highlight**.
**Figma link:** https://www.figma.com/design/H968IpS2Bu9ifKeCWNFYw0/Curious-Connect?node-id=0%3A1&t=jkBeE1XMrdtEK2U9-1

## **Requirements:-**

Should be responsive. And responsive design should look something like this on mobile devices:

![image](https://github.com/Curious-Ecosystem/Curious-Connect/assets/168666000/15d8478e-f120-44b5-b4fa-fdda18dc5c10)

## **Instructions**

You can start working on it by taking latest pull from main branch

- [ ] Please read the contributors guidelines [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the code of conduct [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to join onboarding group for knowledge flow and direct conversation and support from admins
- [ ] **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the screenshots and video of the development work once it is done 
- [ ] Contributions more than 3 will be awarded a certificate of appreciation from curious ecosystem 
- [ ] please mail to ([admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in)) for claiming certificate and please attach your issue number

Respect Co Developers And Please Reach-out to admins if any issues

**Comment by hars-21** [comment]
Please assign me. I'll work on it.

**Comment by CDCHarshit** [comment]
@hars-21 you can start working on this issue.

**Comment by annoy004** [comment]
can you assign me this one

**Comment by hars-21** [comment]
@CDCHarshit @thecuriousteam Please review my PR. #222

**Comment by madhurajituri** [comment]
HI. Please can you assign me. I will add the image background using the library and keep in mind about the responsiveness of the page.

**Comment by hars-21** [comment]
@CDCHarshit Please review the linked pr #222 and tell me if any changes to be done and if not please merge it. Thanks!

**Comment by hars-21** [comment]
@CDCHarshit @thecuriousteam Please close this issue as completed
