### ISSUE TITLE
[JoinRoom.jsx] - Create a JoinRoom.jsx for the landing page component.

### ISSUE THREAD

**Issue by CDCRishabh** [Curious-Ecosystem/Curious-Connect#19]
## **Task Description**

In this Issue we have to create the JoinRoom Component i.e. the component where you will be able to create your room name as well as proceed further to join/create the meeting

## **Requirements:-**

Should be responsive.

## **Goals and objectives**

To achieve the required output.

## **Branch Name**
PR Should be made in feature/InitialUIdesign Branch.
For more information, please read our [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).

## **Deadline**
13/05/2024

## **Priority**
High

## Additional Details
In order to understand the flow of the design here is the link of the [Figma file](https://www.figma.com/file/H968IpS2Bu9ifKeCWNFYw0/Untitled?type=design&node-id=0-1&mode=design).

## **Instructions**

You can start working on it by taking latest pull from main branch

- [ ] Please read the contributors guidelines [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the code of conduct [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to join onboarding group for knowledge flow and direct conversation and support from admins
- [ ] **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the screenshots and video of the development work once it is done 
- [ ] Contributions more than 3 will be awarded a certificate of appreciation from curious ecosystem 
- [ ] please mail to ([admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in)) for claiming certificate and please attach your issue number

Respect Co Developers And Please Reach-out to admins if any issues

**Comment by tusharyadav11** [comment]
i would like to contribute for it

**Comment by agxmbedi** [comment]
I am Agamjot singh. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!

**Comment by CDCDhruv** [comment]
## *Instructions*

You can start working on it by taking latest pull from main branch

- [ ] Please read the contributors guidelines [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the code of conduct [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to join onboarding group for knowledge flow and direct conversation and support from admins
- [ ] *Link* [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the screenshots and video of the development work once it is done 
- [ ] Contributions more than 3 will be awarded a certificate of appreciation from curious ecosystem 
- [ ] please mail to ([admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in)) for claiming certificate and please attach your issue number

Respect Co Developers And Please Reach-out to admins if any issues

**Comment by yash-tyagi-2003** [comment]
I have done various projects in React.js and won hackathons in this Domain. I will be a great choice for this project and thus I request you to assign this to me for contribution under GSSOC 2024.

**Comment by agxmbedi** [comment]
I am Agamjot Singh. Under GSSOC'24, I would like to work on this issue.
Please assign me this!!

**Comment by CDCDhruv** [comment]
## **Instructions**

You can start working on it by taking latest pull from main branch

- [ ] Please read the contributors guidelines [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the code of conduct [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to join onboarding group for knowledge flow and direct conversation and support from admins
- [ ] **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the screenshots and video of the development work once it is done 
- [ ] Contributions more than 3 will be awarded a certificate of appreciation from curious ecosystem 
- [ ] please mail to ([admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in)) for claiming certificate and please attach your issue number

Respect Co Developers And Please Reach-out to admins if any issues

**Comment by CDCDhruv** [comment]
@agxmbedi and @yash-tyagi-2003 please read the instructions.

**Comment by tusharyadav11** [comment]
@CDCRohitSharmax00 i would be grateful if you would assign it to me

**Comment by manpreet244** [comment]
assign me this issue pls

**Comment by alpharsh** [comment]
I am reaching out to express my keen interest in leading the Curious Connect project. With a strong background in HTML, CSS, JavaScript, React, TailwindCSS, etc, I am confident in my ability to contribute significantly to this innovative initiative.
