### ISSUE TITLE
[FeatureCardSection.jsx] - Make feature cards mobile responsive in FeatureCardSection.jsx for landing page

### ISSUE THREAD

**Issue by CDCHarshit** [Curious-Ecosystem/Curious-Connect#191]
## **Task Description**

This issue involves making feature cards responsive in FeatureCardSection.jsx for a landing page.

This is the current design:

![image](https://github.com/Curious-Ecosystem/Curious-Connect/assets/168666000/1edf861b-53ff-4c0d-9d78-903cc4563606)

And we need such a design:

![image](https://github.com/Curious-Ecosystem/Curious-Connect/assets/168666000/3b03f265-7204-4419-b54d-bbfb7abdf2c7)

**For your reference:** https://www.figma.com/design/H968IpS2Bu9ifKeCWNFYw0/Curious-Connect?node-id=720%3A2&t=jkBeE1XMrdtEK2U9-1

## **Instructions**

You can start working on it by taking latest pull from main branch

- [ ] Please read the contributors guidelines [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the code of conduct [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to join onboarding group for knowledge flow and direct conversation and support from admins
- [ ] **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the screenshots and video of the development work once it is done 
- [ ] Contributions more than 3 will be awarded a certificate of appreciation from curious ecosystem 
- [ ] please mail to ([admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in)) for claiming certificate and please attach your issue number

Respect Co Developers And Please Reach-out to admins if any issues

**Comment by hars-21** [comment]
Please assign it to me. I'll work on it

**Comment by CDCHarshit** [comment]
@hars-21 you can start working on this issue.

**Comment by hars-21** [comment]
hey @CDCHarshit I have already made a PR. #214  , please review it and let me know if any changes to be made.

**Comment by CDCHarshit** [comment]
@hars-21 Yeah, we are reviewing the PR. And soon you will get the update from our side. Till then stay tuned.

**Comment by hars-21** [comment]
Sure

**Comment by CDCHarshit** [comment]
The issue with the components making feature cards responsive in **FeatureCardSection.jsx** for a landing page has been resolved.

Thank you for your patience and contributions :)
