### ISSUE TITLE
[Feature] <write a small description here>

### ISSUE THREAD

**Issue by UjjwalSaini07** [Curious-Ecosystem/Curious-Connect#193]
### Description

There is No Button on footer to go again to home page

### Screenshots

![image](https://github.com/Curious-Ecosystem/Curious-Connect/assets/73696489/9afdc772-f523-4010-81ff-813d01f34d14)

### Checklist

- [X] I have checked the existing [issues](https://github.com/Curious-Ecosystem/Curious-Connect/issues).
- [X] I have read the [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md)
- [X] I have read the [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [X] I joined onboarding group for knowledge flow and direct conversation and support from admins  [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done 
- [x] If you need any help please join the default  ([Google Meet Link](https://meet.google.com/bwp-aasw-xbk))

**Comment by Adhil523** [comment]
@thecuriousteam 
please assign this to me as i have worked this out in my pr for responsive navbar #127

**Comment by abcd-aakarsh** [comment]
brother this issue is already created by me please check
