### ISSUE TITLE
[Feature] Adding list of contributors image under readme

### ISSUE THREAD

**Issue by Arpcoder** [Curious-Ecosystem/Curious-Connect#200]
### Description

List of contributors image under readme

### Screenshots

![Screenshot 2024-05-18 124533](https://github.com/Curious-Ecosystem/Curious-Connect/assets/100352419/00334629-f891-4f9e-a041-b7eec8a9f2f5)

### Checklist

- [X] I have checked the existing [issues](https://github.com/Curious-Ecosystem/Curious-Connect/issues).
- [X] I have read the [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md)
- [X] I have read the [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [X] I joined onboarding group for knowledge flow and direct conversation and support from admins  [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done 
- [X] If you need any help please join the default  ([Google Meet Link](https://meet.google.com/bwp-aasw-xbk))

**Comment by thecuriousteam** [comment]
@Arpcoder you can start working on it

## **Instructions**

You can start working on it by taking latest pull from main branch

- [ ] **Please raise pull request to `main`**
- [ ] Please read the **contributors guidelines** [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the **code of conduct** [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to **join onboarding group** for knowledge flow and direct conversation and support from admins
- [ ] **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the **screenshots and video of the development work** once it is done 
- [ ] Contributions more than **3 will be awarded a certificate of appreciation** from curious ecosystem 
- [ ] please mail to [admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in) for claiming certificate and please attach your issue number

if any help required reach-out to admins or mentors in the onboarding group default meeting link and approach to admins - **GOOGLE MEET** [Issue Discussion Google Meet](https://meet.google.com/bwp-aasw-xbk)

Respect Co Developers And Please Reach-out to admins if any issues

**Comment by Arpcoder** [comment]
> @Arpcoder you can start working on it
> 
> ## **Instructions**
> You can start working on it by taking latest pull from main branch
> 
> * [ ]  **Please raise pull request to `main`**
> * [ ]  Please read the **contributors guidelines** [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
> * [ ]  Please follow the **code of conduct** [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
> * [ ]  Don't Forget to **join onboarding group** for knowledge flow and direct conversation and support from admins
> * [ ]  **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
> * [ ]  Please attach the **screenshots and video of the development work** once it is done
> * [ ]  Contributions more than **3 will be awarded a certificate of appreciation** from curious ecosystem
> * [ ]  please mail to [admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in) for claiming certificate and please attach your issue number
> 
> if any help required reach-out to admins or mentors in the onboarding group default meeting link and approach to admins - **GOOGLE MEET** [Issue Discussion Google Meet](https://meet.google.com/bwp-aasw-xbk)
> 
> Respect Co Developers And Please Reach-out to admins if any issues

Thank you for approving this issue. Please add gssoc, level labels to it.

**Comment by somrima-09** [comment]
Hi. Under GSSOC'24, I would like to work on this issue.
Please Assign me this task.
I am looking forward to do this in min. time with max. efficient.

**Comment by Arpcoder** [comment]
@thecuriousteam Please add gssoc and level2 labels to this issue as well, else my score for this won't be counted. Thank you!

**Comment by Arpcoder** [comment]
> @thecuriousteam Please add gssoc and level2 labels to this issue as well, else my score for this won't be counted. Thank you!

@thecuriousteam Please consider this.
