### ISSUE TITLE
[DOCS]: Enhance Readme 

### ISSUE THREAD

**Issue by aasthakourav20** [Curious-Ecosystem/Curious-Connect#206]
### Issue Description

The README file is the first thing users and contributors see when they visit your repository. It serves several key purposes:

Introduction and Overview: It provides a clear and concise introduction to your project, explaining what it does, its purpose, and why it’s valuable.
Installation Instructions: It guides users on how to set up and install the project on their local machines, ensuring they can quickly get started.
Usage Guidelines: It offers detailed instructions on how to use the project, including examples and common use cases.
Contribution Information: It informs potential contributors on how they can contribute to the project, including any guidelines or requirements they should follow.
License Information: It specifies the licensing terms under which the project is distributed, ensuring users and contributors understand their rights and obligations.
Kindly assign this issue to me under GSSoc'24.

### Checklist

- [X] I have checked the existing [issues](https://github.com/Curious-Ecosystem/Curious-Connect/issues).
- [X] I have read the [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md)
- [X] I have read the [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [X] I joined onboarding group for knowledge flow and direct conversation and support from admins  [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done 
- [X] If you need any help please join the default  ([Google Meet Link](https://meet.google.com/bwp-aasw-xbk))

**Comment by thecuriousteam** [comment]
You can start working on it @aasthakourav20

**Comment by thecuriousteam** [comment]
## **Instructions**

You can start working on it by taking latest pull from main branch

- [ ] **Please raise pull request to `main`**
- [ ] Please read the **contributors guidelines** [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the **code of conduct** [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to **join onboarding group** for knowledge flow and direct conversation and support from admins
- [ ] **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the **screenshots and video of the development work** once it is done 
- [ ] Contributions more than **3 will be awarded a certificate of appreciation** from curious ecosystem 
- [ ] please mail to [admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in) for claiming certificate and please attach your issue number

if any help required reach-out to admins or mentors in the onboarding group default meeting link and approach to admins - **GOOGLE MEET** [Issue Discussion Google Meet](https://meet.google.com/bwp-aasw-xbk)

Respect Co Developers And Please Reach-out to admins if any issues

**Comment by thecuriousteam** [comment]
you can start working on this @aasthakourav20

**Comment by 22-0304** [comment]
Can I do this

**Comment by 22-0304** [comment]
Can you assign me this issue @thecuriousteam
