### ISSUE TITLE
[Feature] : Adding Animated icons In the Navbar

### ISSUE THREAD

**Issue by SadafKausar2025** [Curious-Ecosystem/Curious-Connect#217]
### Description

adding these animated icons gives new good look to the page

### Screenshots

https://github.com/Curious-Ecosystem/Curious-Connect/assets/137484958/230a7eae-a613-4d36-a9bf-05c9ffee02a2

### Checklist

- [X] I have checked the existing [issues](https://github.com/Curious-Ecosystem/Curious-Connect/issues).
- [X] I have read the [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md)
- [X] I have read the [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [X] I joined onboarding group for knowledge flow and direct conversation and support from admins  [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done 
- [X] If you need any help please join the default  ([Google Meet Link](https://meet.google.com/bwp-aasw-xbk))

**Comment by SadafKausar2025** [comment]
hey @gnnandan 
Can you please assign me this issue?

**Comment by cpratik1307** [comment]
I am thrilled to be participating in GirlScript Summer of Code 2k24 as a passionate computer science student with a keen interest in web development. I am eager to contribute to your project and leverage my skills to make meaningful contributions. I look forward to collaborating with you and the team to create impactful solutions.
@SadafKausar2025  Sir, I would really like to work on this issue under Gssoc'24, so please assign it to me.

**Comment by 143divya** [comment]
Can you please assign this issue to me under Gssoc'24? I want to work on this.
