### ISSUE TITLE
[BUG] UI : No personalised favicon

### ISSUE THREAD

**Issue by SaranshBangar** [Curious-Ecosystem/Curious-Connect#227]
### Description

The website still uses the default Vite icon as the favicon

### Any additional information?

I am a contributor under GSSoC, please label the issue accordingly

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing [issues](https://github.com/Curious-Ecosystem/Curious-Connect/issues).
- [X] I have read the [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md)
- [X] I have read the [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [X] I joined onboarding group for knowledge flow and direct conversation and support from admins  [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done 
- [X] If you need any help please join the default  ([Google Meet Link](https://meet.google.com/bwp-aasw-xbk))
- [X] I am willing to work on this issue (optional).

**Comment by SaranshBangar** [comment]
Resolved in PR #228

**Comment by PratikMane0112** [comment]
Already raised check #169

**Comment by CDCNaman** [comment]
@SaranshBangar Thanks for raising the issue but please from next time check whether the issue is already created or not
