### ISSUE TITLE
Making Social Icons More Attractive

### ISSUE THREAD

**Issue by UjjwalSaini07** [Curious-Ecosystem/Curious-Connect#245]
### Description

Doing Animations and Hovering or Use this website make icon more attractive and looking cool
`https://fontawesome.com/`
On this footer page

### Screenshots

![image](https://github.com/Curious-Ecosystem/Curious-Connect/assets/73696489/da99376a-8e71-42bb-b618-b28361b9d129)

### Checklist

- [X] I have checked the existing [issues](https://github.com/Curious-Ecosystem/Curious-Connect/issues).
- [X] I have read the [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md)
- [X] I have read the [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [X] I joined onboarding group for knowledge flow and direct conversation and support from admins  [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done 
- [X] If you need any help please join the default  ([Google Meet Link](https://meet.google.com/bwp-aasw-xbk))

**Comment by anuragnegi000** [comment]
add labels and Kindly assign this issue to me

**Comment by PrakarshSingh5** [comment]
Please assign this project to me

**Comment by UjjwalSaini07** [comment]
Work completed
