### ISSUE TITLE
Responsive Navbar

### ISSUE THREAD

**Issue by UjjwalSaini07** [Curious-Ecosystem/Curious-Connect#255]
### Description

Make A good and attractive responsive navbar in Mobile view it looking very ugly. and if possible so also do some animations.

### Screenshots

![image](https://github.com/Curious-Ecosystem/Curious-Connect/assets/73696489/364be4fd-39a6-405b-8b51-dae63cdb7565)

### Checklist

- [X] I have checked the existing [issues](https://github.com/Curious-Ecosystem/Curious-Connect/issues).
- [X] I have read the [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md)
- [X] I have read the [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [X] I joined onboarding group for knowledge flow and direct conversation and support from admins  [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done 
- [X] If you need any help please join the default  ([Google Meet Link](https://meet.google.com/bwp-aasw-xbk))

**Comment by anuragnegi000** [comment]
Review PR #256

**Comment by UjjwalSaini07** [comment]
Good Effort Brother Now this issue is Solved so i closed that.
