### ISSUE TITLE
[BUG] Favicon not visible

### ISSUE THREAD

**Issue by avanimathur** [Curious-Ecosystem/Curious-Connect#257]
### Description

A favicon has been added via the HTML file however it is not visible.
The path needs to be updated and the image be saved with .ico extension

### Screenshots

![WhatsApp Image 2024-06-03 at 14 59 07](https://github.com/Curious-Ecosystem/Curious-Connect/assets/151984867/41352cd2-4c4e-46f5-b388-510dcd17f791)

### Any additional information?

This is under GSSOC'24

### Checklist

- [X] I have checked the existing [issues](https://github.com/Curious-Ecosystem/Curious-Connect/issues).
- [X] I have read the [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md)
- [X] I have read the [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [x] I joined onboarding group for knowledge flow and direct conversation and support from admins  [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done 
- [X] If you need any help please join the default  ([Google Meet Link](https://meet.google.com/bwp-aasw-xbk))
- [X] I am willing to work on this issue (optional).

**Comment by Deepali109** [comment]
Please assign me this issue under gssoc24.

**Comment by yashi301** [comment]
Please assign this issue to me

**Comment by yashi301** [comment]
Please assign this issue to me I've worked on this type of issues
