### ISSUE TITLE
create a scroll-to-top button on bottom left of website

### ISSUE THREAD

**Issue by Riddhi162** [Curious-Ecosystem/Curious-Connect#260]
### Description

This will give a seeamless experience to the user and will make the user reach the top of website at one click only. 

### Checklist

- [X] I have checked the existing [issues](https://github.com/Curious-Ecosystem/Curious-Connect/issues).
- [X] I have read the [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md)
- [X] I have read the [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [X] I joined onboarding group for knowledge flow and direct conversation and support from admins  [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done 
- [X] If you need any help please join the default  ([Google Meet Link](https://meet.google.com/bwp-aasw-xbk))

**Comment by saurabhbakolia** [comment]
I would like to work on it. 
Please assign this issue to me.

**Comment by prachitavse** [comment]
Kindly assign me this issue under GSSOC' 24.
I would like to work on this issue.
