### ISSUE TITLE
Improve the UI of navbar .

### ISSUE THREAD

**Issue by Riddhi162** [Curious-Ecosystem/Curious-Connect#261]
### Description

We can add glassmorphism effect to the navbar. Also we can make it sticky. We can improve the on hover effect on the links in navbar. I'm a GSSOC'24 contributor.

### Checklist

- [X] I have checked the existing [issues](https://github.com/Curious-Ecosystem/Curious-Connect/issues).
- [X] I have read the [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md)
- [X] I have read the [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [X] I joined onboarding group for knowledge flow and direct conversation and support from admins  [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done 
- [X] If you need any help please join the default  ([Google Meet Link](https://meet.google.com/bwp-aasw-xbk))

**Comment by saurabhbakolia** [comment]
Hey, I would like to work on it.

**Comment by kashi-verma** [comment]
I would like to work on this issue. So I request you to @thecuriousteam  to assign this issue to me.

Thank you

**Comment by kashi-verma** [comment]
yes i want to work on this issue , can you assign this to me?

**Comment by Riyasharma1311** [comment]
please assign me this issue.

**Comment by kashi-verma** [comment]
Pls assign me this issue .@curious-Ecosystem

**Comment by kashi-verma** [comment]
yes , can you assign this to me

**Comment by kashi-verma** [comment]
I am interested in , please assign this to me
