### ISSUE TITLE
[DOCS] README File is not properly organized.

### ISSUE THREAD

**Issue by anijit18** [Curious-Ecosystem/Curious-Connect#274]
### Issue Description

The Prerequisites Section of the file is not organized.
All the information to run the project in our local is written in the same paragraph which decreased the readability of the project.

### Screenshots or Examples (if applicable)

![image](https://github.com/user-attachments/assets/ba9805e9-ce2b-41ea-bce0-f7e426dedafd)

### Proposed Solution (optional)

I will organize the Prerequisites Section properly by adding a new line after each instruction and properly adding the spaces.

### Checklist

- [X] I have checked the existing [issues](https://github.com/Curious-Ecosystem/Curious-Connect/issues).
- [X] I have read the [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md)
- [X] I have read the [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [X] I joined onboarding group for knowledge flow and direct conversation and support from admins  [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done 
- [X] If you need any help please join the default  ([Google Meet Link](https://meet.google.com/bwp-aasw-xbk))

**Comment by anijit18** [comment]
I want to work on this issue. Please assign it to me under GSSOC.

**Comment by anijit18** [comment]
@CDCHarshit  @CDCRishabh Kindly assign this issue to me under GSSOC.

**Comment by Sanjanadas45** [comment]
please assign this to me.
