### ISSUE TITLE
Set server option in vite to open browser automaticallly

### ISSUE THREAD

**Issue by niteshbca** [Curious-Ecosystem/Curious-Connect#28]
## **Describe the bug**
in vite set server option `open: true` so that when we run dev command then browser will open autometically

check here-https://vitejs.dev/config/server-options#server-open

### **Expected behavior**
 
![image](https://github.com/Curious-Ecosystem/Curious-Connect/assets/138958926/7b6e2857-cb93-46d8-9fea-deea50c4738c)

### **Environment (Please Mention if it is environment specific issue):**
 - Device: [e.g. iPhone6, PC, Laptop]
 - Screen Size: [e.g., 1920x1080, 1366x768]
 - OS: [e.g. iOS, Linux]

## **Instructions**

Stay you can start working on it by taking latest pull from main branch

- [ x] Please read the contributors guidelines [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ x] Please follow the code of conduct [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ x] Don't Forget to join onboarding group for knowledge flow and direct conversation and support from admins
- [ x] **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ x] Please attach the screenshots and video of the development work once it is done 
- [x ] Contributions more than 3 will be awarded a certificate of appreciation from curious ecosystem 
- [ x] please mail to ([admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in)) for claiming certificate and please attach your issue number

Respect Co Developers And Please Reach-out to admins if any issues

**Comment by niteshbca** [comment]
@thecuriousteam @CDCNaman please assign me?

**Comment by thecuriousteam** [comment]
@niteshbca you can start working on it

**Comment by thecuriousteam** [comment]
Please raise this pull request to branch `feature/InitialUIDesign` for this Sprint 1

**Comment by CDCNaman** [comment]
@niteshbca Sorry for the confusion but we have dropped the idea of merging into feature branch as many of the contributors are having problem in doing this.

Please once again raise your PR against main branch

**Comment by niteshbca** [comment]
> @CDCNaman Please sir tell me whether the work has been merged.

**Comment by niteshbca** [comment]
@thecuriousteam Please sir tell me whether the work has been merged.
