### ISSUE TITLE
[UI Design] - Finalized UI Design

### ISSUE THREAD

**Issue by thecuriousteam** [Curious-Ecosystem/Curious-Connect#5]

**Comment by CDCJanhavi** [comment]
Landing page UI design for curious connect.  [https://www.figma.com/design/H968IpS2Bu9ifKeCWNFYw0/Untitled?node-id=0%3A1&t=EbsPbXmzT3k8KDLx-1](url)
![WhatsApp Image 2024-05-08 at 21 55 27](https://github.com/Curious-Ecosystem/Curious-Connect/assets/159638163/8289d6ed-1644-464e-9fa2-618f8237bc7d)

**Comment by anirudh-why** [comment]
Please assign me this issue under GSSOC'24.
As a mern stack developer I can handle this well.

**Comment by kohi9noor** [comment]
anirudh bro you can work on the issue without assign because there is no pr so you can make pr after solving the issue it's not it is not a always good practice to wait every time an issue is assigned to me or not you skip and focus on solving the issue and make pr okay.
