### ISSUE TITLE
Feat: Automate greeting using Github bot 🤖

### ISSUE THREAD

**Issue by dakshsinghrathore** [Curious-Ecosystem/Curious-Connect#50]
### Describe the feature

As the contributor count rises on the repo, it becomes increasingly challenging for maintainers to personally greet and encourage each contributor for their valuable input. Equally important is the reminder for them to review the project's contribution guidelines.

### PR greeting message ⬇️ 

![CleanShot_2024-05-11_at_14 39 402x](https://github.com/hereisSwapnil/ExamTime/assets/115932772/f39a24ed-dfd9-46c4-8b14-24281aa1711e)

### ISSUE greeting message ⬇️ 

![CleanShot_2024-05-11_at_14 40 482x](https://github.com/hereisSwapnil/ExamTime/assets/115932772/1b275744-94b8-4199-81f4-1ef42dfd84a8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by dakshsinghrathore** [comment]
@thecuriousteam I would like to work on this issue, kindly assign me

**Comment by thecuriousteam** [comment]
@dakshsinghrathore You can start working on it

## **Instructions**

You can start working on it by taking latest pull from main branch

- [ ] **Please raise pull request to `feature/InitialUIDesign`**
- [ ] Please read the **contributors guidelines** [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the **code of conduct** [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to **join onboarding group** for knowledge flow and direct conversation and support from admins
- [ ] **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the **screenshots and video of the development work** once it is done 
- [ ] Contributions more than **3 will be awarded a certificate of appreciation** from curious ecosystem 
- [ ] please mail to ([admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in)) for claiming certificate and please attach your issue number

if any help required reach-out to admins or mentors in the onboarding group default meeting link and approach to admins - [https://meet.google.com/bwp-aasw-xbk]

Respect Co Developers And Please Reach-out to admins if any issues

**Comment by thecuriousteam** [comment]
Please reach-out to admins [Curious Connect Project Admins](https://wa.link/4b9c7o) with your issue number and don't forget to join [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)

**Comment by AnitSarkar123** [comment]
Can I also work on that issue @thecuriousteam

**Comment by thecuriousteam** [comment]
@AnitSarkar123 you can start working on it

**Comment by thecuriousteam** [comment]
any updates? @AnitSarkar123 @dakshsinghrathore

**Comment by dakshsinghrathore** [comment]
> any updates? @AnitSarkar123 @dakshsinghrathore 

Will create the PR by tonight
