### ISSUE TITLE
[LandingPage.jsx] - Create a responsive header for curious-connect

### ISSUE THREAD

**Issue by CDCSheetal** [Curious-Ecosystem/Curious-Connect#6]
Shortly we'll inform the menus which we'll be using .

**Comment by sarthak-stranger** [comment]
Hi, Can you please Assign this issue to me, I have so experience in designing so I will create a responsive header with some extra features and also give the UI according to Main page.XZ
*

**Comment by thecuriousteam** [comment]
Please join to the CDC - GSSOC 2024 group to know more and keep interactive with admins of the project

Link - https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN

#LetsGrowAllTogether

**Comment by thecuriousteam** [comment]
**Instructions**

Stay you can start working on it by taking latest pull from main branch
Don't Forget to join onboarding group for knowledge flow and direct conversation and support from other developers link [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
Please attach the screenshots and video of the development work once it is done
Contributions more than 3 will be awarded a certificate of appreciation from curious ecosystem please mail to ([admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in)) for claiming certificate and please attach your issue number
Respect Co Developers And Please Reachout to admins if any issues

**Comment by thecuriousteam** [comment]
@sarthak-stranger and @akshatsingh523 you guys joined group?

**Comment by sarthak-stranger** [comment]
@thecuriousteam yes i have joined.

**Comment by sarthak-stranger** [comment]
Thank you for assigning me the issue.
Can you please share your discord id or something else for talk regarding work

**Comment by thecuriousteam** [comment]
@sarthak-stranger You are in the group?

**Comment by sarthak-stranger** [comment]
No, but I have requested

**Comment by thecuriousteam** [comment]
7338146217 please reachout to admin @sarthak-stranger

**Comment by sarthak-stranger** [comment]
Ok

**Comment by Husan7** [comment]
hello sir, i am husandeep singh here GSSoC 24 Contributor.  I will create a responsive header with amazing extra features , you can check it on my project. Can you please assign me this issue

**Comment by thecuriousteam** [comment]
@Husan7 

## **Instructions**

You can start working on it by taking latest pull from main branch

- [ ] **Please raise pull request to `feature/InitialUIDesign`**
- [ ] Please read the **contributors guidelines** [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the **code of conduct** [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to **join onboarding group** for knowledge flow and direct conversation and support from admins
- [ ] **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the **screenshots and video of the development work** once it is done 
- [ ] Contributions more than **3 will be awarded a certificate of appreciation** from curious ecosystem 
- [ ] please mail to ([admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in)) for claiming certificate and please attach your issue number

if any help required reach-out to admins or mentors in the onboarding group default meeting link and approach to admins - [https://meet.google.com/bwp-aasw-xbk]

Respect Co Developers And Please Reach-out to admins if any issues

**Comment by gnnandan** [comment]
I want to work on this issue

**Comment by thecuriousteam** [comment]
## **Instructions**

You can start working on it by taking latest pull from main branch

- [ ] **Please raise pull request to `feature/InitialUIDesign`**
- [ ] Please read the **contributors guidelines** [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the **code of conduct** [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to **join onboarding group** for knowledge flow and direct conversation and support from admins
- [ ] **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the **screenshots and video of the development work** once it is done 
- [ ] Contributions more than **3 will be awarded a certificate of appreciation** from curious ecosystem 
- [ ] please mail to ([admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in)) for claiming certificate and please attach your issue number

if any help required reach-out to admins or mentors in the onboarding group default meeting link and approach to admins - [https://meet.google.com/bwp-aasw-xbk]

Respect Co Developers And Please Reach-out to admins if any issues

**Comment by sarthak-stranger** [comment]
@thecuriousteam i am designing navbar and also i want suggestion how i design landing page like should i make carousel or simple effective image. what you think?? Tell me which design you want?

**Comment by thecuriousteam** [comment]
Please reach-out to admins [Curious Connect Project Admins](https://wa.link/hrn0z8) with your issue number and don't forget to join [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)

Your Default Meeting Link - https://meet.google.com/bwp-aasw-xbk
