### ISSUE TITLE
Error Response Handling with Base Code in Auth Service

### ISSUE THREAD

**Issue by CDCNaman** [Curious-Ecosystem/Curious-Connect#81]
## **Describe the bug**
There is Problem in Error Handling Middleware and Base Code of Auth Service. Register Route is returning empty json data

## **Screenshots**
![image](https://github.com/Curious-Ecosystem/Curious-Connect/assets/149701907/1c24c340-e3a9-4582-b8d3-ec49ec7ccaa9)

### **To Reproduce**
1. Post Sample json data to `/api/sign-up` Route.

### **Expected behavior**
1. It should return the JWT Token as of now in Json response.
2. On Occurring any Server Side Error, return the error in response with proper Error Handling.

## **Additional context**
1. In Future, we will parse the token in Cookies.
2. Also add Refresh and Access Token

## **Instructions**

Stay you can start working on it by taking latest pull from main branch

- [ ] Please read the contributors guidelines [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the code of conduct [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to join onboarding group for knowledge flow and direct conversation and support from admins
- [ ] **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the screenshots and video of the development work once it is done 
- [ ] Contributions more than 3 will be awarded a certificate of appreciation from curious ecosystem 
- [ ] please mail to ([admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in)) for claiming certificate and please attach your issue number

Respect Co Developers And Please Reach-out to admins if any issues in the onboarding group

**Comment by mehtakevan** [comment]
Can you please assign this issue to me

**Comment by CDCNaman** [comment]
@mehtakevan you can start working on it.

**Comment by CDCNaman** [comment]
@mehtakevan Also you can refer to this article as well for best Error Handling practices in Express https://dev.to/qbentil/how-to-write-custom-error-handler-middleware-in-expressjs-using-javascript-29j1

**Comment by Akki019** [comment]
I want to work on this

**Comment by thecuriousteam** [comment]
@Akki019 you can start working on this

## **Instructions**

You can start working on it by taking latest pull from main branch

- [ ] **Please raise pull request to `main`**
- [ ] Please read the **contributors guidelines** [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the **code of conduct** [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to **join onboarding group** for knowledge flow and direct conversation and support from admins
- [ ] **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the **screenshots and video of the development work** once it is done 
- [ ] Contributions more than **3 will be awarded a certificate of appreciation** from curious ecosystem 
- [ ] please mail to [admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in) for claiming certificate and please attach your issue number

if any help required reach-out to admins or mentors in the onboarding group default meeting link and approach to admins - **GOOGLE MEET** [Issue Discussion Google Meet](https://meet.google.com/bwp-aasw-xbk)

Respect Co Developers And Please Reach-out to admins if any issues
