### ISSUE TITLE
[BUG] Complete the 'Legal Section' from the footer

### ISSUE THREAD

**Issue by yashmandi** [Curious-Ecosystem/Curious-Connect#83]
### Description
In the footer section, when a user clicks on any of the option from 'Legal Section', he is redirected to the same page at the top, instead he should redirected to actual page.

### Proposed Solution
I can create a basic page for 'Privacy Policy' and 'Terms of Service' present under the Legal Section in footer.
Request you to assign this task to me under GSSOC '24

## **Instructions**

Stay you can start working on it by taking latest pull from main branch

- [ ] Please read the contributors guidelines [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the code of conduct [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to join onboarding group for knowledge flow and direct conversation and support from admins
- [ ] **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the screenshots and video of the development work once it is done 
- [ ] Contributions more than 3 will be awarded a certificate of appreciation from curious ecosystem 
- [ ] please mail to ([admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in)) for claiming certificate and please attach your issue number

Respect Co Developers And Please Reach-out to admins if any issues

**Comment by CDCNaman** [comment]
hey @thecuriousteam is this issue resolved?  You have merged the #91 PR
