### ISSUE TITLE
[HeroSection.jsx] - Design responsive hero section for curious connect

### ISSUE THREAD

**Issue by thecuriousteam** [Curious-Ecosystem/Curious-Connect#92]
![image](https://github.com/Curious-Ecosystem/Curious-Connect/assets/120193300/c2ff7b4a-0f4e-458a-b75d-097d17dbd0e4)

**Comment by niteshbca** [comment]
@thecuriousteam  Please, can you assign me?

**Comment by alpharsh** [comment]
@thecuriousteam please assign this project to me as i have good command over the frontend.

**Comment by Shravani246** [comment]
@thecuriousteam I am reaching out to express my keen interest in leading the Curious Connect project. With a strong background in HTML, CSS, JavaScript, ReactJS, NodeJS, and MongoDB, coupled with extensive experience in utilizing advanced technologies like WebRTC, Mediasoup, and SocketIO, I am confident in my ability to contribute significantly to this innovative initiative.

**Comment by thecuriousteam** [comment]
@Shravani246 Please reach-out admins

## **Instructions**

You can start working on it by taking latest pull from main branch

- [ ] **Please raise pull request to `main`**
- [ ] Please read the **contributors guidelines** [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the **code of conduct** [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to **join onboarding group** for knowledge flow and direct conversation and support from admins
- [ ] **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the **screenshots and video of the development work** once it is done 
- [ ] Contributions more than **3 will be awarded a certificate of appreciation** from curious ecosystem 
- [ ] please mail to [admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in) for claiming certificate and please attach your issue number

if any help required reach-out to admins or mentors in the onboarding group default meeting link and approach to admins - **GOOGLE MEET** [Issue Discussion Google Meet](https://meet.google.com/bwp-aasw-xbk)

Respect Co Developers And Please Reach-out to admins if any issues

**Comment by maha-sachin** [comment]
@thecuriousteam , I'd like to work on this issue.

**Comment by amnipriyasowrirajan** [comment]
I wanna work on this  @thecuriousteam

**Comment by thecuriousteam** [comment]
@amnipriyasowrirajan you can start working on this

## **Instructions**

You can start working on it by taking latest pull from main branch

- [ ] **Please raise pull request to `main`**
- [ ] Please read the **contributors guidelines** [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [ ] Please follow the **code of conduct** [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [ ] Don't Forget to **join onboarding group** for knowledge flow and direct conversation and support from admins
- [ ] **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [ ] Please attach the **screenshots and video of the development work** once it is done 
- [ ] Contributions more than **3 will be awarded a certificate of appreciation** from curious ecosystem 
- [ ] please mail to [admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in) for claiming certificate and please attach your issue number

if any help required reach-out to admins or mentors in the onboarding group default meeting link and approach to admins - **GOOGLE MEET** [Issue Discussion Google Meet](https://meet.google.com/bwp-aasw-xbk)

Respect Co Developers And Please Reach-out to admins if any issues

**Comment by thecuriousteam** [comment]
@alpharsh You also can start working on it

**Comment by niteshbca** [comment]
![Screenshot 2024-05-14 201648](https://github.com/Curious-Ecosystem/Curious-Connect/assets/138958926/aeef0384-6044-4b7e-9222-aaf7c83a226d)
Responsive hreo section please assign me task.

**Comment by niteshbca** [comment]
please sir feedback
