### ISSUE TITLE
Filter genuine email

### ISSUE THREAD

**Issue by pankaj-bind** [Curious-Ecosystem/Curious-Connect#99]
## Feature Description
I will add a feature so that no one could create an account using **temporary or disposable email**.

### Problem or Opportunity
In your application anyone can enter using **temporary or disposable email**, which is possibly a security threat.

### Proposed Solution
I will add a feature so that no one could create an account using **temporary or disposable email**.
It will allow only genuine users in your database.
It will help to avoid any bot.

### Additional Context
Assign me this work under GSSoC24, I will implement it.

## **Instructions**

Stay you can start working on it by taking latest pull from main branch

- [x] Please read the contributors guidelines [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
- [x] Please follow the code of conduct [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
- [x] Don't Forget to join onboarding group for knowledge flow and direct conversation and support from admins
- [x] **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
- [x] Please attach the screenshots and video of the development work once it is done 
- [x] Contributions more than 3 will be awarded a certificate of appreciation from curious ecosystem 
- [x] please mail to ([admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in)) for claiming certificate and please attach your issue number

Respect Co Developers And Please Reach-out to admins if any issues

**Comment by CDCNaman** [comment]
@pankaj-bind How will you implement this? Means I want to know more about your approach. Will You Create a Utility function to check whether it is a disposable email or not?

**Comment by pankaj-bind** [comment]
> @pankaj-bind How will you implement this? Means I want to know more about your approach. Will You Create a Utility function to check whether it is a disposable email or not?

I will use an API which is free it will first checks is the email genuine or not, if yes then it proceeds otherwise, breaks operation and shows a popup "invalid email"
I have tried this, and this feature is very unique.
